@host = https://localhost:7151
@barcode = RMARS3234567890123456789M

### Create parcel
POST {{host}}/parcels
Content-Type: application/json

{
  "barcode": "RMARS3234567890123456789M",
  "sender": "Anders Hejlsberg",
  "recipient": "Elon Musk",
  "deliveryService": "Express",
  "contents": "Signed C# language specification and a birthday card"
}

### Get parcel
GET {{host}}/parcels/{{barcode}}

### Update parcel
PATCH {{host}}/parcels/{{barcode}}
Content-Type: application/json

{
  "newStatus": "OnRocketToMars"
}
