@RM.Mars.ParcelTracking_HostAddress = https://localhost:7151

POST {{RM.Mars.ParcelTracking_HostAddress}}/parcels
Content-Type: application/json

{
  "barcode": "RMARS3234567890123456789M",
  "sender": "Anders Hejlsberg",
  "recipient": "Elon Musk",
  "deliveryService": "Express",
  "contents": "Signed C# language specification and a birthday card"
}

###

@barcode=RMARS3234567890123456789M
GET {{RM.Mars.ParcelTracking_HostAddress}}/parcels/{{barcode}}

###

@barcode=RMARS3234567890123456789M
PATCH {{RM.Mars.ParcelTracking_HostAddress}}/parcels/{{barcode}}
Content-Type: application/json
{
  "newStatus" : "OnRocketToMars"
}
###